# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "赵铁刚"
description: > # this means to ignore newlines until "email:"
   一个菜鸟的成长日记

email: 450964002@qq.com
#blog logo
logo: "/assets/images/dflogo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_asdfgt.jpg"

name: '赵铁刚'
author: '赵铁刚'
author_image: "/assets/images/author.jpg"

paginate:	５



#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	qq空间
    url:	https://user.qzone.qq.com/450964002
    desc: 我的ｑｑ空间

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/z450964002
    desc:	点赞～～～
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
